services:
  - type: web
    name: supermarket-cl
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.0.0
      - key: SUPERMARKET_ENCRYPTION_KEY
        generateValue: true
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
